### PR TITLE
Dark Theme

### PR DESCRIPTION
**Pull request by Magvin**
Hi Please review

### CODE REVIEW

**Comment by jakswa** [comment]
I took a quick look and i see some problems. I can look more in depth later on.

- [x] double header on the station view ("Stations" at  the top when looking at individual station):
image
it used to look like:
image

- [x] icon alignment looks changed -- arrows aren't vertically centered, and train icon is cut off
image
it used to look like:
image

- [x] i haven't included package-lock.json in this repo because it is so huge. I'm ok eating the risks/concerns around not having it. Would you be ok removing that from this PR? It ballooned your PR to 12k lines :(

**Comment by Magvin** [comment]
Okay, I will remove package-lock.json. 
Do you want to display toggle Dark theme only on the Main component or sub comp as well? 
Need to workarounds about icon alignment leave this with me

**Comment by jakswa** [comment]
> Do you want to display toggle Dark theme only on the Main component or sub comp as well?

1. I'm ok with the easiest path for now -- having it only on the main component. Or at the bottom of the page? Could complicate things having it down there.
2. A better solution feels like a new "settings" icon at the  bottom of the page, possibly taking the spot of my face here (people don't need my twitter link):
image

So, if you want to go the extra mile, it could be down at the bottom of the page. The quick fix of only having it on the landing page works. I can come through  and put it where I want later.

**Comment by Magvin** [comment]
Hey.  All done:) toggle is now in the bottom of the app

**Comment by jakswa** [comment]
I think we can call your work done. I've got some oddities still. I do not think they are your fault. I bet I can fix them easy enough after merging. Thank you again!

thank_you


### remaining oddities, so i don't forget:
I'm looking at some wonky UI still, but I think this is either my fault (bad CSS practices :grimacing:) or Material UI's fault (npm packages got upgraded after a long time, noticing different CSS classes, etc).

The top row here shows the differences (this is me toggling between production + development view):
img

**Comment by Magvin** [comment]
Cool let me know if you need any help with this in future :) Keep in touch ;)

**Comment by jakswa** [comment]
Ooops I meant to merge this. I have a small branch on top of this to edit the CSS a little. It won't get deployed until I work out the kinks!

**Pull request merged**
